[tasks.dev]
description = "Start the library build watcher"
depends = "clean"
run = "tsdown --watch"

[tasks.build]
description = "Start the library build"
depends = "clean"
run = "tsdown"

[tasks.clean]
description = "Delete the dist directory"
run = "rm -rf dist"

[tasks.fmt]
description = "Format the entire project"
run = "prettier --write ."

[tasks.typecheck]
description = "Typecheck the entire project"
run = "tsgo --noEmit"
